---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "default.yml"
  tags: always

- include_tasks: debconf.yml
  when: ansible_os_family == "Debian"

- name: Install postfix
  package:
    name: "{{ postfix_packages }}"
    state: present

- name: Postfix main options
  when: postfix_main_cfg is defined and postfix_main_cfg
  with_dict: "{{ postfix_main_cfg  }}"
  postfix:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  notify: restart postfix